<?xml version="1.0" ?>
<robot xmlns:xacro="https://www.ros.org/wiki/xacro" >
    <xacro:property name="PI" value="3.1415926535897931"/>
    <xacro:property name="location_x" value="0.25" />
    <xacro:property name="location_y" value="0" />
    <xacro:property name="location_z" value="0.5" />

    <xacro:property name="bar_x" value="0.02" />
    <xacro:property name="bar_y" value="0.2" />
    <xacro:property name="bar_z" value="1.0" />
    <xacro:property name="bar_m" value="0.1" />

    <xacro:property name="vslider_x" value="0.02" />
    <xacro:property name="vslider_y" value="0.5" />
    <xacro:property name="vslider_z" value="0.05" />
    <xacro:property name="vslider_m" value="0.1" />

    <xacro:property name="hslider_x" value="0.02" />
    <xacro:property name="hslider_y" value="0.05" />
    <xacro:property name="hslider_z" value="0.05" />
    <xacro:property name="hslider_m" value="0.1" />

    <xacro:macro name="operate_device_macro" params="parent robotname">
      <joint name="joint_support_bar" type="fixed">
        <origin xyz="${location_x} ${location_y} ${location_z}" rpy="0 0 0"/>
        <parent link="${parent}"/>
        <child link="link_bar"/>
      </joint>

      <link name="link_bar">
        <visual>
          <origin xyz="${bar_x/2} 0 0" rpy="0 0 0" />
          <geometry>
            <box size="${bar_x} ${bar_y} ${bar_z}"/>
          </geometry>
        </visual>
        <collision>
          <origin xyz="${bar_x/2} 0 0" rpy="0 0 0" />
          <geometry>
            <box size="${bar_x} ${bar_y} ${bar_z}"/>
          </geometry>
        </collision>
        <inertial>
          <mass value="${bar_m}"/>
          <origin xyz="${bar_x/2} 0 0" rpy="0 0 0"/>
          <inertia ixx="${1/12*bar_m*(bar_y*bar_y+bar_z*bar_z)}" ixy="0" ixz="0" iyy="${1/12*bar_m*(bar_z*bar_z+bar_x*bar_x)}" iyz="0" izz="${1/12*bar_m*(bar_x*bar_x+bar_y*bar_y)}"/>
        </inertial>
      </link>

      <joint name="joint_bar_vslider" type="prismatic">
        <origin xyz="${bar_x} 0 0" rpy="0 0 0"/>
        <parent link="link_bar"/>
        <child link="link_vslider"/>
        <axis xyz="0 0 1"/>
        <limit upper="0.9" lower="-0.4" effort="100.0" velocity="1.0"/>
        <dynamics damping="1.0" friction="30.0"/>
      </joint>

      <link name="link_vslider">
        <visual>
          <origin xyz="${vslider_x/2} 0 0" rpy="0 0 0" />
          <geometry>
            <box size="${vslider_x} ${vslider_y} ${vslider_z}"/>
          </geometry>
        </visual>
        <collision>
          <origin xyz="${vslider_x/2} 0 0" rpy="0 0 0" />
          <geometry>
            <box size="${vslider_x} ${vslider_y} ${vslider_z}"/>
          </geometry>
        </collision>
        <inertial>
          <mass value="${vslider_m}"/>
          <origin xyz="${vslider_x/2} 0 0" rpy="0 0 0"/>
          <inertia ixx="${1/12*vslider_m*(vslider_y*vslider_y+vslider_z*vslider_z)}" ixy="0" ixz="0" iyy="${1/12*vslider_m*(vslider_z*vslider_z+vslider_x*vslider_x)}" iyz="0" izz="${1/12*vslider_m*(vslider_x*vslider_x+vslider_y*vslider_y)}"/>
        </inertial>
      </link>

      <joint name="joint_slider_slider" type="fixed">
        <origin xyz="${vslider_x} 0 0" rpy="0 0 0"/>
        <parent link="link_vslider"/>
        <child link="link_hslider"/>
        <axis xyz="0 1 0"/>
        <limit upper="0.225" lower="-0.225" effort="100.0" velocity="0.5"/>
        <dynamics damping="1.0" friction="30.0"/>
      </joint>

      <link name="link_hslider">
        <visual>
          <origin xyz="${hslider_x/2} 0 0" rpy="0 0 0" />
          <geometry>
            <box size="${hslider_x} ${hslider_y} ${hslider_z}"/>
          </geometry>
        </visual>
        <collision>
          <origin xyz="${hslider_x/2} 0 0" rpy="0 0 0" />
          <geometry>
            <box size="${hslider_x} ${hslider_y} ${hslider_z}"/>
          </geometry>
        </collision>
        <inertial>
          <mass value="${hslider_m}"/>
          <origin xyz="${hslider_x/2} 0 0" rpy="0 0 0"/>
          <inertia ixx="${1/12*hslider_m*(hslider_y*hslider_y+hslider_z*hslider_z)}" ixy="0" ixz="0" iyy="${1/12*hslider_m*(hslider_z*hslider_z+hslider_x*hslider_x)}" iyz="0" izz="${1/12*hslider_m*(hslider_x*hslider_x+hslider_y*hslider_y)}"/>
        </inertial>
      </link>

      <joint name="joint_slider_finger" type="fixed">
        <origin xyz="${hslider_x} 0 0" rpy="0 0 0"/>
        <parent link="link_hslider"/>
        <child link="link_finger"/>
      </joint>

      <link name="link_finger">
        <visual>
          <origin xyz="0.05 0 0" rpy="0 0 0" />
          <geometry>
            <box size="0.1 0.02 0.02"/>
          </geometry>
        </visual>
        <collision>
          <origin xyz="0.05 0 0" rpy="0 0 0" />
          <geometry>
            <box size="0.1 0.02 0.02"/>
          </geometry>
        </collision>
        <inertial>
          <mass value="0.02"/>
          <origin xyz="0.05 0 0" rpy="0 0 0" />
          <inertia ixx="0.000001" ixy="0" ixz="0" iyy="0.000017" iyz="0" izz="0.000017"/>
        </inertial>
      </link>

      <joint name="joint_finger_tip" type="fixed">
        <origin xyz="0.1 0 0" rpy="0 0 0"/>
        <parent link="link_finger"/>
        <child link="link_tip"/>
      </joint>
      <link name="link_tip">
        <visual>
          <origin xyz="0.005 0 -0.015" rpy="0 0 0" />
          <geometry>
            <box size="0.01 0.02 0.05"/>
          </geometry>
        </visual>
        <collision>
          <origin xyz="0.005 0 -0.015" rpy="0 0 0" />
          <geometry>
            <box size="0.01 0.02 0.05"/>
          </geometry>
        </collision>
        <inertial>
          <mass value="0.001"/>
          <origin xyz="0.005 0 -0.015" rpy="0 0 0" />
          <inertia ixx="0.00000001" ixy="0" ixz="0" iyy="0.000000017" iyz="0" izz="0.0000000017"/>
        </inertial>
      </link>

      <transmission name="vertical_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="joint_bar_vslider">
          <hardwareInterface>EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="vertical_motor">
          <hardwareInterface>EffortJointInterface</hardwareInterface>
          <mechanicalReduction>1</mechanicalReduction>
        </actuator>
      </transmission>

      <!-- <transmission name="horizontal_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="joint_slider_slider">
          <hardwareInterface>EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="horizontal_motor">
          <hardwareInterface>EffortJointInterface</hardwareInterface>
          <mechanicalReduction>1</mechanicalReduction>
        </actuator>
      </transmission> -->

      <gazebo reference="link_bar">
        <material>Gazebo/Orange</material>
      </gazebo>
      <gazebo reference="link_vslider">
        <material>Gazebo/Orange</material>
      </gazebo>
      <gazebo reference="link_hslider">
        <material>Gazebo/Orange</material>
      </gazebo>

      <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
          <robotNamespace>/${robotname}</robotNamespace>
          <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
          <legacyModeNS>true</legacyModeNS>
        </plugin>
      </gazebo>

    </xacro:macro>
</robot>
