<?xml version="1.0" ?>

<robot xmlns:xacro="https://www.ros.org/wiki/xacro" >
    <xacro:property name="PI" value="3.1415926535897931"/>
    <xacro:property name="chassis_x" value="0.4" />
    <xacro:property name="chassis_y" value="0.4" />
    <xacro:property name="chassis_z" value="0.2" />
    <xacro:property name="chassis_m" value="30" />
    <xacro:property name="wheel_r" value="0.2"/>
    <xacro:property name="wheel_l" value="0.08"/>
    <xacro:property name="wheel_m" value="0.5"/>
    <xacro:property name="caster_r" value="0.1"/>
    <xacro:property name="caster_m" value="0.1"/>
    <xacro:property name="wheelbase" value="0.3" />
    <xacro:property name="track" value="0.38" />

    <xacro:property name="support_x" value="0.4" />
    <xacro:property name="support_y" value="0.4" />
    <xacro:property name="support_z" value="1.0" />
    <xacro:property name="support_m" value="1" />

    <!-- main triwheeler link -->
    <xacro:macro name="triwheeler_base_macro">
      <!-- Used for fixing robot to Gazebo 'base_link'-->
      <link name="world"/>
      <joint name="joint_world_chassis" type="floating">
        <parent link="world"/>
        <child link="link_chassis"/>
      </joint>

      <link name="link_chassis">
        <visual>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
            <box size="${chassis_x} ${chassis_y} ${chassis_z}"/>
          </geometry>
        </visual>
        <collision>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
            <box size="${chassis_x} ${chassis_y} ${chassis_z}"/>
          </geometry>
        </collision>
        <inertial>
          <mass value="${chassis_m}"/>
          <origin rpy="0 0 0" xyz="0 0 0"/>
          <inertia ixx="${1/12*chassis_m*(chassis_y*chassis_y+chassis_z*chassis_z)}" ixy="0" ixz="0" iyy="${1/12*chassis_m*(chassis_z*chassis_z+chassis_x*chassis_x)}" iyz="0" izz="${1/12*chassis_m*(chassis_x*chassis_x+chassis_y*chassis_y)}"/>
        </inertial>
      </link>

      <joint name="joint_chassis_lwheel" type="continuous">
        <origin xyz="-${wheelbase/2} ${track/2} 0" rpy="0 0 0" />
        <parent link="link_chassis"/>
        <child link="link_lwheel"/>
        <axis xyz="0 1 0" rpy="0 0 0" />
      </joint>

      <link name="link_lwheel">
        <visual>
          <origin rpy="${PI/2} 0 0" xyz="0 0 0"/>
          <geometry>
            <cylinder length="${wheel_l}" radius="${wheel_r}"/>
          </geometry>
        </visual>
        <collision>
          <origin rpy="${PI/2} 0 0" xyz="0 0 0" />
          <geometry>
            <cylinder length="${wheel_l}" radius="${wheel_r}"/>
          </geometry>
        </collision>
        <inertial>
          <mass value="${wheel_m}"/>
          <origin rpy="${PI/2} 0 0" xyz="0 0 0"/>
          <inertia ixx="${1/12*wheel_m*(3*wheel_r*wheel_r+wheel_l*wheel_l)}" ixy="0" ixz="0" iyy="${1/12*wheel_m*(3*wheel_r*wheel_r+wheel_l*wheel_l)}" iyz="0" izz="${1/2*wheel_m*wheel_r*wheel_r}"/>
        </inertial>
      </link>

      <joint name="joint_chassis_rwheel" type="continuous">
        <origin xyz="-${wheelbase/2} -${track/2} 0" rpy="0 0 0" />
        <parent link="link_chassis"/>
        <child link="link_rwheel"/>
        <axis xyz="0 1 0" rpy="0 0 0" />
      </joint>

      <link name="link_rwheel">
        <visual>
          <origin rpy="${PI/2} 0 0" xyz="0 0 0"/>
          <geometry>
            <cylinder length="${wheel_l}" radius="${wheel_r}"/>
          </geometry>
        </visual>
        <collision>
          <origin rpy="${PI/2} 0 0" xyz="0 0 0" />
          <geometry>
            <cylinder length="${wheel_l}" radius="${wheel_r}"/>
          </geometry>
        </collision>
        <inertial>
          <mass value="${wheel_m}"/>
          <origin rpy="${PI/2} 0 0" xyz="0 0 0"/>
          <inertia ixx="${1/12*wheel_m*(3*wheel_r*wheel_r+wheel_l*wheel_l)}" ixy="0" ixz="0" iyy="${1/12*wheel_m*(3*wheel_r*wheel_r+wheel_l*wheel_l)}" iyz="0" izz="${1/2*wheel_m*wheel_r*wheel_r}"/>
        </inertial>
      </link>

      <joint name="joint_chassis_caster" type="fixed">
        <origin rpy="0 0 0" xyz="${wheelbase/2} 0 -${chassis_z/2}"/>
        <parent link="link_chassis"/>
        <child link="link_caster"/>
      </joint>

      <link name="link_caster">
        <visual>
          <origin rpy="0 0 0" xyz="0 0 0"/>
          <geometry>
            <sphere radius="${caster_r}"/>
          </geometry>
        </visual>
        <collision>
          <origin rpy=" 0 0 0" xyz="0 0 0"/>
          <geometry>
            <sphere radius="${caster_r}"/>
          </geometry>
        </collision>
        <inertial>
          <mass value="${caster_m}"/>
          <origin rpy="0 0 0" xyz="0 0 0"/>
          <inertia ixx="${2/5*caster_m*caster_r*caster_r}" ixy="0" ixz="0" iyy="${2/5*caster_m*caster_r*caster_r}" iyz="0" izz="${2/5*caster_m*caster_r*caster_r}"/>
        </inertial>
      </link>

      <joint name="joint_chassis_support" type="fixed">
        <origin rpy="0 0 0" xyz="0 0 ${chassis_z/2}"/>
        <parent link="link_chassis"/>
        <child link="link_support"/>
      </joint>

      <link name="link_support">
        <visual>
          <origin xyz="0 0 ${support_z/2}" rpy="0 0 0" />
          <geometry>
            <box size="${support_x} ${support_y} ${support_z}"/>
          </geometry>
        </visual>
        <collision>
          <origin xyz="0 0 ${support_z/2}" rpy="0 0 0" />
          <geometry>
            <box size="${support_x} ${support_y} ${support_z}"/>
          </geometry>
        </collision>
        <inertial>
          <mass value="${support_m}"/>
          <origin rpy="0 0 0" xyz="0 0 0"/>
          <inertia ixx="${1/12*support_m*(support_y*support_y+support_z*support_z)}" ixy="0" ixz="0" iyy="${1/12*support_m*(support_z*support_z+support_x*support_x)}" iyz="0" izz="${1/12*support_m*(support_x*support_x+support_y*support_y)}"/>
        </inertial>
      </link>

      <!--Gazebo-->

      <!-- differential_drive_controller -->
      <gazebo>
        <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
          <legacyMode>false</legacyMode>
          <alwaysOn>true</alwaysOn>
          <updateRate>100</updateRate>
          <leftJoint>joint_chassis_lwheel</leftJoint>
          <rightJoint>joint_chassis_rwheel</rightJoint>
          <wheelSeparation>${chassis_y}+${wheel_l}</wheelSeparation>
          <wheelDiameter>2*${wheel_r}</wheelDiameter>
          <wheelTorque>90</wheelTorque>
          <!--wheelAcceleration>${wheel_accel}</wheelAcceleration-->
          <commandTopic>cmd_vel</commandTopic>
          <odometryTopic>odom</odometryTopic>
          <odometryFrame>odom</odometryFrame>
          <robotBaseFrame>link_chassis</robotBaseFrame>
        </plugin>
      </gazebo>

      <gazebo reference="link_chassis">
        <material>Gazebo/White</material>
      </gazebo>

      <gazebo reference="link_lwheel">
        <mu1>1</mu1>
        <mu2>1</mu2>
        <material>Gazebo/Black</material>
      </gazebo>

      <gazebo reference="link_rwheel">
        <mu1>1</mu1>
        <mu2>1</mu2>
        <material>Gazebo/Black</material>
      </gazebo>

      <gazebo reference="link_caster">
        <mu1>0</mu1>
        <mu2>0</mu2>
        <material>Gazebo/Black</material>
      </gazebo>

    </xacro:macro>
</robot>
