obstacle_range: 2.0
raytrace_range: 3.0
footprint: [[0.25, 0.25],[-0.25, 0.25],[-0.25, -0.25],[0.25,-0.25]] # counter-closkwise
# footprint: [[0.2, 0.24],[0.2,-0.24],[-0.2, -0.24],[-0.2, 0.24]] # clockwise
#robot_radius: ir_of_robot

robot_base_frame: "link_chassis"

transform_tolerance: 0.2  # second delay
update_frequency: 5.0
publish_frequency: 1.0
resolution: 0.05

# layers
inflation:
  cost_scaling_factor: 3.0
  inflation_radius: 0.1

obstacles:
  observation_sources: laser_scan_sensor
  laser_scan_sensor: {sensor_frame: link_hokuyo, data_type: LaserScan, topic: laser/scan, marking: true, clearing: true}
