obstacle_range: 5.0
raytrace_range: 8.0
footprint: [[-0.2, 0.24], [-0.2, -0.24], [0.2,-0.24], [0.2, 0.24]]
#robot_radius: ir_of_robot
inflation_radius: 0.3
observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: link_hokuyo, data_type: LaserScan, topic: laser/scan, marking: true, clearing: true}
