global_costmap:
  global_frame: "map"
  robot_base_frame: "link_chassis"
  transform_tolerance: 0.2  # second delay
  update_frequency: 10.0
  publish_frequency: 0.0
  static_map: true
  rolling_window: false # must be false if static_map is used
  plugins:
    - {name: static_map, type: "costmap_2d::StaticLayer"}
