local_costmap:
  global_frame: odom
  robot_base_frame: link_chassis
  update_frequency: 10.0
  publish_frequency: 10.0
  static_map: false
  rolling_window: true
  width: 4.0
  height: 4.0
  resolution: 0.05
  transform_tolerance: 0.05
  obstacle_layer:
    enabled: true
    obstacle_range: 5.0
    raytrace_range: 4.5
    inflation_radius: 0.5
    track_unknown_space: true
    combination_method: 1
    observation_sources: laser_scan_sensor
    laser_scan_sensor: {sensor_frame: link_hokuyo, data_type: LaserScan, topic: laser/scan, marking: true, clearing: true}
