local_costmap:
  global_frame: "odom"
  static_map: false
  rolling_window: true
  width: 4.0
  height: 4.0
  plugins:
    - {name: obstacles, type: "costmap_2d::VoxelLayer"}
    - {name: inflation, type: "costmap_2d::InflationLayer"}
